### ISSUE TITLE
Macro expension failure when transforming coproducts within case classes

### ISSUE THREAD

**Issue by yoohaemin** [scalalandio/chimney#108]
Affected versions: 0.3.0+ (0.2.1 works fine)

Reproducton:
```scala
package example

import io.scalaland.chimney.dsl._

case class Foo(i: Foo.A)
object Foo {

  sealed trait A extends Product with Serializable
  case object A0 extends A

}

case class Bar(i: Bar.A)
object Bar {

  sealed trait A extends Product with Serializable
  case object A0 extends A

}


object Hello extends App {

  val bar = Foo(Foo.A0).transformInto[Bar]

  println(bar)
}
```

```
[info] Compiling 1 Scala source to /tmp/chimney-bugreport/target/scala-2.12/classes ...                               
[error] /tmp/chimney-bugreport/src/main/scala/example/Hello.scala:24:38: exception during macro expansion:               
[error] scala.ScalaReflectionException: <none> is not a method                                                            
[error]         at scala.reflect.api.Symbols$SymbolApi.asMethod(Symbols.scala:240)                                           
[error]         at scala.reflect.api.Symbols$SymbolApi.asMethod$(Symbols.scala:234)                                   
[error]         at scala.reflect.internal.Symbols$SymbolContextApiImpl.asMethod(Symbols.scala:106)                    
[error]         at io.scalaland.chimney.internal.DerivationGuards.destinationJavaBean(DerivationGuards.scala:51)
[error]         at io.scalaland.chimney.internal.DerivationGuards.destinationJavaBean$(DerivationGuards.scala:48)
[error]         at io.scalaland.chimney.internal.ChimneyBlackboxMacros.destinationJavaBean(ChimneyBlackboxMacros.scala:5)
[error]         at io.scalaland.chimney.internal.DerivationGuards.canTryDeriveTransformer(DerivationGuards.scala:71)
[error]         at io.scalaland.chimney.internal.DerivationGuards.canTryDeriveTransformer$(DerivationGuards.scala:61)
[error]         at io.scalaland.chimney.internal.ChimneyBlackboxMacros.canTryDeriveTransformer(ChimneyBlackboxMacros.scala:5)
[error]         at io.scalaland.chimney.internal.TransformerMacros$$anonfun$3.applyOrElse(TransformerMacros.scala:416)     
[error]         at io.scalaland.chimney.internal.TransformerMacros$$anonfun$3.applyOrElse(TransformerMacros.scala:407)          
[error]         at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:145)                                  
[error]         at scala.collection.immutable.List.foreach(List.scala:392)                                                           
[error]         at scala.collection.TraversableLike.collect(TraversableLike.scala:274)                                               
[error]         at scala.collection.TraversableLike.collect$(TraversableLike.scala:272)                 
[error]         at scala.collection.immutable.List.collect(List.scala:327)                                                
[error]         at io.scalaland.chimney.internal.TransformerMacros.resolveTargetArgTrees(TransformerMacros.scala:407)      
[error]         at io.scalaland.chimney.internal.TransformerMacros.resolveTargetArgTrees$(TransformerMacros.scala:401)
[error]         at io.scalaland.chimney.internal.ChimneyBlackboxMacros.resolveTargetArgTrees(ChimneyBlackboxMacros.scala:5)
[error]         at io.scalaland.chimney.internal.TransformerMacros.expandDestinationCaseClass(TransformerMacros.scala:345)  
[error]         at io.scalaland.chimney.internal.TransformerMacros.expandDestinationCaseClass$(TransformerMacros.scala:321)
[error]         at io.scalaland.chimney.internal.ChimneyBlackboxMacros.expandDestinationCaseClass(ChimneyBlackboxMacros.scala:5)
[error]         at io.scalaland.chimney.internal.TransformerMacros.$anonfun$expandTransformerTree$2(TransformerMacros.scala:74)
[error]         at scala.Option.getOrElse(Option.scala:138)
[error]         at io.scalaland.chimney.internal.TransformerMacros.expandTransformerTree(TransformerMacros.scala:57)
[error]         at io.scalaland.chimney.internal.TransformerMacros.expandTransformerTree$(TransformerMacros.scala:49)
[error]         at io.scalaland.chimney.internal.ChimneyBlackboxMacros.expandTransformerTree(ChimneyBlackboxMacros.scala:5)
[error]         at io.scalaland.chimney.internal.TransformerMacros.genTransformer(TransformerMacros.scala:23)
[error]         at io.scalaland.chimney.internal.TransformerMacros.genTransformer$(TransformerMacros.scala:12)
[error]         at io.scalaland.chimney.internal.ChimneyBlackboxMacros.genTransformer(ChimneyBlackboxMacros.scala:5)
[error]         at io.scalaland.chimney.internal.ChimneyBlackboxMacros.deriveTransformerImpl(ChimneyBlackboxMacros.scala:19)
[error]   val bar = Foo(Foo.A0).transformInto[Bar]
[error]                                      ^                                      
[error] one error found  
[error] (Compile / compileIncremental) Compilation failed                                                 
[error] Total time: 0 s, completed Jun 13, 2019 5:35:28 PM
```

**Comment by yoohaemin** [comment]
I don't have any experience with macros, so this looks interesting. I'll try to see if I can fix it myself.

**Comment by krzemin** [comment]
Hi @yoohaemin, thanks for reporting.
Looks like there is missing check for casting symbol as method symbol. It should be relatively easy to fix.
If you open a PR, could you please include a test in `IssuesSpec` that fails on the current implementation, but passes after fix is applied?

**Comment by yoohaemin** [comment]
Sure, thanks for the tip!

**Comment by yoohaemin** [comment]
Hi, I think I would need some help here :sweat_smile: 

As you suggested, I changed
```scala
primaryConstructor.isPublic && 
  primaryConstructor.asMethod.paramLists == List(Nil) && 
  to.beanSetterMethods.nonEmpty
```
to
```scala
primaryConstructor.isPublic && 
  primaryConstructor.isMethod &&
  primaryConstructor.asMethod.paramLists == List(Nil) && 
  to.beanSetterMethods.nonEmpty
```

and I get this when compiling the above example:
```
[info] Updating chimneyJVM...
[info] Done updating.
[info] Compiling 15 Scala sources to /home/haemin/projects/chimney/chimney/.jvm/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 8 Scala sources to /home/haemin/projects/chimney/chimney/.jvm/target/scala-2.12/test-classes ...
[warn] an unexpected type representation reached the compiler backend while compiling IssuesSpec.scala: (private[this] Bar$module$2: scala.runtime.LazyRef)io.scalaland.chimney.IssuesSpec$Bar$5.type. If possible, please file a bug on https://github.com/scala/bug/issues.
[error] Error while emitting IssuesSpec.scala
[error] (private[this] Bar$module$2: scala.runtime.LazyRef)io.scalaland.chimney.IssuesSpec$Bar$5.type (of class scala.reflect.internal.Types$MethodType)
[warn] one warning found
[error] one error found
[error] (chimneyJVM / Test / compileIncremental) Compilation failed
[error] Total time: 8 s, completed Jun 13, 2019 9:40:56 PM
1. Waiting for source changes in project root... (press enter to interrupt)
```

I would very much appreciate any tips on how to proceed in cases like this, thanks in advance :smile:

**Comment by krzemin** [comment]
Docs for `.primaryConstructor` say:
```
*  Known issues: Due to scala/bug#8367, primaryConstructor may return unexpected results
*  when called for Java classes (for some vague definition of a "Java class", which apparently
*  not only includes javac-produced classfiles, but also consists of classes defined in
*  Scala programs under the java.lang package). What's even worse, for some Java classes
*  we can't even guarantee stability of the return value - depending on your classloader configuration
*  and/or JDK version you might get different primaryConstructor for the same ClassSymbol.
*  We have logged these issues at scala/bug#8193.
```

and:

```
// TODO: scala/bug#8193 I think we should only return a non-empty symbol if called for Scala classes
// returning something for traits and module classes is outright confusing
// This, however, will require some refactoring in the compiler, so I'll leave it for later
// as at the moment we don't have time or risk tolerance for that
```

So most probably you're right that this is compiler's corner case.

But I have few rough ideas that you may want to try out:
- first check if primary constructor is not empty symbol (`primaryConstructor != NoSymbol`)
- if this leads to exception anyway, you may want to wrap the whole block in `Try(...)` and `.getOrElse(false)`
